services:
  - type: web
    name: med-chron-api
    runtime: python
    repo: https://github.com/Jeetkachhela/Med_chron.git
    rootDir: backend
    buildCommand: |
      pip install -r requirements.txt && playwright install chromium --with-deps
    startCommand: chmod +x ./start.sh && ./start.sh
    envVars:
      - key: SQLALCHEMY_DATABASE_URI
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.9"
