"""add_past_treatments_json_column

Revision ID: da693d01b5d8
Revises: c5de0b1ea870
Create Date: 2026-04-27 14:42:10.239083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da693d01b5d8'
down_revision: Union[str, Sequence[str], None] = 'c5de0b1ea870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('past_treatments_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'past_treatments_json')
    # ### end Alembic commands ###
